title: Ally's Saucy Site

author:
  name: Ally Hong
  email: allyhong@mit.edu

description: > # this means to ignore newlines until "show_excerpts:"
  Welcome to my saucy site, where you'll find all sorts of saucy projects, blogs, and even music!

# set to true to show excerpts on the homepage
show_excerpts: false 

collections:
  projects:
    output: true
  posts:
    output: true

# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%b %-d, %Y"

# generate social links in footer
social_links:
  github:  allymhong
  facebook: allyminjuu
  instagram: allyminju
  linkedin: allyhong
  youtube: UClfv9P9D1cyZbtWo7ohu4-Q

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- posts.md
# - projects.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-relative-links